[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build]
    command = "npm run build && cp _redirects dist"
    publish = "dist"

[[redirects]]
    from = "/*"
    to = "/index.html/:splat"
    status = 200

[[redirects]]
    from = "/blog/*"
    to = "/index.html?path=blog/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
